Resources:
    DictionaryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:custom.default.env}-${self:custom.table.dictionary}"
        AttributeDefinitions:
          - AttributeName: label
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: label
            KeyType: HASH
          - AttributeName: category
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 100
          WriteCapacityUnits: 5
    RulesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${self:custom.default.env}-${self:custom.table.rules}"
        AttributeDefinitions:
          - AttributeName: ruleTag
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: ruleTag
            KeyType: HASH
          - AttributeName: type
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 50
          WriteCapacityUnits: 5